---

name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:

  publish:
    permissions:
      contents: write

    uses: ./.github/workflows/workflow-publish.yaml
    with:
      version: current
      alias: current
