---

name: ci

on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      # - name: brubru
      #   shell: python
      #   run: |
      #     # python

      #     import cane

      #     a = '12'

      #     # /python

      - name: build
        run: |
          # sh

          set -x

          mkdir -p src/idp_docs
          touch src/idp_docs/__init__.py

          git config --global user.email "$(git log --format='%ae' $GITHUB_SHA -n1)"
          git config --global user.name "$(git log --format='%an' $GITHUB_SHA -n1)"

          uv run \
            mike deploy \
              --update-aliases \
              --push \
              ciao xxx

          # /sh

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    # environment:
    #   name: github-pages
    # #   url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
