---

name: publish current

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  publish:
    uses: ./.github/workflows/workflow-publish.yaml
    permissions:
      contents: write
    with:
      version: current
