---

name: publish a branch
run-name: publish `${{ github.ref_name }}` branch

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  publish:
    uses: ./.github/workflows/workflow-publish.yaml
    permissions:
      contents: write
    with:
      version: ${{ github.ref_name }}
